### ISSUE TITLE
package name issues;

### ISSUE THREAD

**Issue by YuAJio** [shadowfaxtech/proSwipeButton#7]
Good moring/noon/afternoon/evening,I saw this View on VisualStudio NuGet ;
   I download this package and is something happend on my Project; It's seem like the package name changed by xamarin , became the In.ShadowFax;  (Last word has been cut,because it's the same as view name )  
but the Register path it's still" in.shadowfax.proswipebutton.ProSwipeButton";
That different led to my Activity Crash....
Could U plz to change the package name or the view name to make them different;
Tks...

**Comment by ishaangarg** [comment]
I'm sorry, changing the package or 'view' name is not possible now because it would break for projects that are already using this library.

I have never worked on Xamarin, so not sure how to help you, but try googling how to stop xamarin from changing package name of an imported module or library..

**Comment by YuAJio** [comment]
okay/// Thank's for your response,I will try that way (≧∇≦)/
